edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Auto"
imports_granularity = "Crate"
reorder_imports = true
group_imports = "StdExternalCrate"
reorder_impl_items = true
use_field_init_shorthand = true
format_code_in_doc_comments = true
wrap_comments = true
comment_width = 80
trailing_comma = "Vertical"
